<a href="https://colab.research.google.com/github/GamalAbouhalima/Introduction-to-Python/blob/main/Introduction_to_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to python


In [ ]:
print("Hello","Gamal")

Hello Gamal


In [ ]:
name=input("What is Your Name? ")
print ("Hello",name)

What is Your Name? Gamal
Hello Gamal


In [ ]:
num1=int (input("Enter number One: "))
num2=int (input("Enter number Two: "))
print("Sum = ",num1+num2)

Enter number One: 10
Enter number Two: 12
Sum =  22


In [ ]:
x="Gamal"
x=25
print(x)

25


#Type Conversion


In [ ]:
x=2
x=float(x)
print(x)

2.0


In [ ]:
x=3.9
x=int(x)
print(x)

3


In [ ]:
b=True
b=int(b)
print(b)

1


In [ ]:
c=True
c=float(c)
print(c)

1.0


In [ ]:
d=9
d=bool(d)
print(d)

True


In [ ]:
d=0
d=bool(d)
print(d)

False


In [ ]:
d=-9
d=bool(d)
print(d)

True


In [ ]:
x=8
x=str(x)
print(x)

8


In [ ]:
y=x+"5"
y

'85'

#Convert from STring to Boolean


In [ ]:
x="Hello"
x=bool(x)
print(x)

True


In [ ]:
x="false"
x=bool(x)
print(x)

True


Convert from String to int or float


In [ ]:
x="5"
x=int(x)
print(x+5)

10


In [ ]:
x="5"
x=float(x)
print(x+5)

10.0


In [ ]:
x="5.5"
x=int(x)
print(x+5)
#you must convert to floate firstly and convert to int

ValueError: invalid literal for int() with base 10: '5.5'

#if condition


In [ ]:
x=int(input("Enter a number: "))
if x > 0:
  print("x is positive ")
elif x == 0:
  print("x is zero")
else:
  print("x is negative")

Enter a number: 0
x is zero


In [ ]:
order=50
member=True
if not (order>100 and member==True):
  print("You have discount 10%")
elif(order>100 and member==False):
  print("You have discount 5%")
else:
  print("No discount")

You have discount 10%


In [ ]:
num=int(input("Enter a number: "))
if num%2==0:
  print("Even")
else:
  print("Odd")

Enter a number: 0
Even


#Simple Calculator

In [31]:
print(" **************** Simple Calculator ****************")
ans="yes"
while(ans=="yes"):
  number1=int(input("Enter First number : "))
  number2=int(input("Enter Second number : "))
  operator=input("Enter operator : ")
  if(operator=='+' or operator=='-' or operator=='*' or operator=='/'or operator=='//' or operator=='%' ):
    def add(number1,number2):
      print(number1+number2)

    def sub(number1,number2):
      print(number1-number2)

    def mal(number1,number2):
      print(number1*number2)

    def div(number1,number2):
      print(number1/number2)

    def divDiv(number1,number2):
      print(number1//number2)

    def mod(number1,number2):
      print(number1 % number2)


    if operator=="+":
      add(number1,number2)

    elif operator=="-":
      sub(number1,number2)

    elif operator=="/":
      div(number1,number2)

    elif operator=="*":
      mal(number1,number2)

    elif operator=="//":
      divDiv(number1,number2)

    elif operator=="%":
      mod(number1,number2)

    else :
      print("Invalid operator")
    ans=input("Do You Want to continue ?")
    ans=ans.lower()
    if(ans=='no'):
      break
print("Thanks for using my calculator")



 **************** Simple Calculator ****************
Enter First number : 14
Enter Second number : 5
Enter operator : +
19
Do You Want to continue ?Yes
Enter First number : 55
Enter Second number : 5
Enter operator : +
60
Do You Want to continue ?No
Thanks for using my calculator


#Loops & Functions


In [ ]:
for i in range(0,101,2):
  print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [ ]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

In [ ]:
def sum(a,b=5):
  print(a+b)

In [ ]:
sum(3)

8


In [ ]:
x=9
y=False
if not (x>0 or y == True):
  print("Yes")
else:
  print("No")


No


In [ ]:
#index
s="Welcome into Python"
len(s)

19

In [ ]:
l_names=['Salma','Gamal','Ali','Kenzy','Nesma','Menna','Mohamed']
for name in l_names:
  print("Hello",name)

Hello Salma
Hello Gamal
Hello Ali
Hello Kenzy
Hello Nesma
Hello Menna
Hello Mohamed


In [ ]:
l_numbers=[]
l_numbers=list(range(1,30))
l_numbers

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [ ]:
l_fruits=['Apple','Mango','Watermelon','Orange','Banana']
for i in range(0,len(l_fruits)):
  print(l_fruits[i])

Apple
Mango
Watermelon
Orange
Banana


In [ ]:
i

4

In [ ]:
count=0
for i in range(0,101,2): # (start , end, step)
  print(i)
  count+=1
print("================================================")
count

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


51

In [ ]:
x=7
while(x>0):
  print(x)
  x-=1

7
6
5
4
3
2
1


In [ ]:
while(True):
  word=input("Enter Word : ")
  if(word=='q' or word=='quit'):
    break
  else:
    print("Try Again ")


Enter Word : 4
Try Again 
Enter Word : 5
Try Again 
Enter Word : a
Try Again 
Enter Word : quit


In [ ]:
x=7
for i in range(0,9):
  if(i==7):
    continue
  else:
    print(i)

0
1
2
3
4
5
6
8


In [ ]:
l=[8,3,6,12,44]
len(l)

5

In [ ]:
count=0
for i in l:
  count+=1;
print(count)

5


In [ ]:
def size(l):
  count=0
  for i in l:
    count+=1
  return count



In [ ]:
size(name)

7

In [ ]:
def Hello(country="France"):
  print("Hello",country)

In [ ]:
Hello()

Hello France


In [ ]:
def add(a,b=8):
  x=a+b;
  return x;

In [ ]:
add(5)

13

In [ ]:
add(5,6)

11

In [ ]:
x="Hello Python"
for i in x:
  print()

H
e
l
l
o
 
P
y
t
h
o
n


In [36]:
l=[1,2,3,4,5]
m=list(map(lambda x:x**2,l))
m

[1, 4, 9, 16, 25]

In [43]:
s="welcome to python world"
s[11:17]

'python'

In [44]:
l=[1,2,3,4,5]
l[1:3]

[2, 3]

In [53]:
l=[]
l.append(1)
l.append(2)
l.append(3)
l

[1, 2, 3]

In [46]:
l.insert(2,7.5)
l

[1, 2, 7.5, 3]

In [55]:
l.append(10)
l

[1, 2, 3, 10]

In [56]:
l.remove(10)  # Remove by value
l

[1, 2, 3]

In [57]:
del l[2]  # Remove by index
l
#

[1, 2]

In [58]:
l[len(l)-1]

2

In [59]:
l[-1]

2

In [77]:
grades=[50,60,70,80,90]
max=grades[0]
for i in grades:
  if(i>max):
    max=i
print(max)

90


#Dictionary

In [87]:
d={'Year':2024,"Month":7,"Day":24}

In [88]:
d.keys()

dict_keys(['Year', 'Month', 'Day'])

In [89]:
d.items()

dict_items([('Year', 2024), ('Month', 7), ('Day', 24)])

In [90]:
for i in d:
  print(i)

Year
Month
Day


#Set

In [93]:
s={8,3,6,12,3,44}
s

{3, 6, 8, 12, 44}

In [94]:
s.add(9)
s

{3, 6, 8, 9, 12, 44}

In [95]:
s.remove(3)
s

{6, 8, 9, 12, 44}

In [96]:
s=set(l)
s

{1, 2}

In [99]:
l1=[1,2,3,4,5]
l2=[2,3,4,5,6]
s1=set(l1)
s2=set(l2)
s3=s1-s2
s3

{1}

#Tuble


In [100]:
t=(1,2,3,4,5)
t

(1, 2, 3, 4, 5)

In [101]:
t[0]

1

#Array

In [107]:
import numpy as np
#1D Array
ar=np.array([1,2,3,4.5,5,False,"hi"])
ar

array(['1', '2', '3', '4.5', '5', 'False', 'hi'], dtype='<U32')

In [145]:
#2D Array
ar2=np.array([[1,2,3],[4,50,6],[7, 8, 20]])
ar2

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8, 20]])

In [109]:
ar2.shape

(2, 3)

In [121]:
ar2[0,0]

1

In [127]:
ar2[1:4]

array([[4, 5, 6],
       [7, 8, 9]])

In [135]:
ar2[0,:]

array([1, 2, 3])

In [146]:
ar2.argmax()

4

In [144]:
ar2.argmin()

0

In [148]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [150]:
import pandas as pd
arr_2D = np.array([['house', 2, 'S', 'yes'],
                   ['apartment', 1, 'N', 'no'],
                   ['villa', 5, 'M', 'yes'],
                   ['villa', 3, 'L', 'yes'],
                   ['house', 'nan', 'N', 'yes'],
                   ['villa', 3, 'N', 'no'],
                   ['apartment', 2, 'M', 'no'],
                   ['apartment', 'nan', 'S', 'no'],
                   ['house', 2, 'S', 'yes'],
                   ['house', 3, 'L', 'yes'],
                   ['villa', 5, 'L', 'no'],
                   ['house', 2, 'N', 'yes'],
                   ['house', 4, 'L', 'no'],
                   ['house', 'nan', 'N', 'yes'],
                   ['house', 3, 'S', 'yes']])

In [ ]:
columns = ['type', "rooms", 'room_size', 'label']

In [ ]:
'''
Create data frame for this array using pandas library and name the columns as
suggested in the columns list , start index from 1 instead of 0 in the dataframe ,
try to convert the room size columns to integers and solve the problem of nan values
'''